name: glow_avatar
description: A Flutter widget that displays circular avatars with a customizable glowing border, perfect for user profiles and UI effects.
version: 1.0.1
homepage: https://github.com/YogeshMoradiya/glow_avatar
repository: https://github.com/YogeshMoradiya/glow_avatar
license: MIT
topics:
  - avatar
  - glow
  - ui

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
